name: GitHub Metrics

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Contribution calendar
        uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics.calendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: yashbajaj02
          base: ""
          plugin_calendar: yes
          plugin_calendar_limit: 1
          output_action: commit

      - name: Achievements
        uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics.achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: yashbajaj02
          base: ""
          plugin_achievements: yes
          plugin_achievements_display: compact
          output_action: commit
